### ISSUE TITLE
bruh wtf

### ISSUE THREAD

**Issue by NyaomiDEV** [SantX27/yu-topy#1]

**Comment by SantX27** [comment]
Wii aa za Japaniizu goburin!
Du yuu habu kei no takatobi oni goroshi
Ai amu eeto Japaniizu goburin
Aka ao kiiro no onizu ando moa
Hai bibitto shatoruuzu guriin oni
Sekushii midiamu baioretto oni
Murasaki dai dai shakunage oni
Ra ra ra ieru kana tunai hyakkiyagyou
Hai tenshon Japaniizu goburin
Doranku happii don don hebereke
Ai amu eeto Japaniizu goburin
Retsu goo tsukimi da utae ya sawage ya
Furoshiki tsutsunde sharu uii nan chara
Hito mo ayakashi mo shaku ni hoshi ukabe
Kuru shuu nai zo kuru shuu nai zo
Bureiku auto de bureikou
![japanese-goblin-suika](https://user-images.githubusercontent.com/15846078/218341593-1ad9e44d-9308-4f1f-ac9c-bf22790ce1e3.gif)

**Comment by NyaomiDEV** [comment]
![image](https://user-images.githubusercontent.com/13177694/219853385-5af475a6-399c-42e3-958b-c77144e0f312.png)
